Initializing GPIO Controll
Initializing GPIO Controll
Initializing BT Controll
Initializing GPIO Controll
Initializing BT Controll
Advertising BT Service on Port 1 // UUID: 1e0ca4ea-299d-4335-93eb-27fcfe7fa848
Starting connect_and_listen loop...
Waiting for connection
Established Connection with ('48:27:EA:0A:C5:14', 1)
BluetoothError occured while waiting or processing command: (104, 'Connection reset by peer')
Traceback (most recent call last):
  File "<string>", line 3, in recv
_bluetooth.error: (104, 'Connection reset by peer')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/repos/vancontrol/raspi/BluetoothController.py", line 61, in _listen
    data = self._client_sock.recv(1024)
  File "<string>", line 5, in recv
bluetooth.btcommon.BluetoothError: (104, 'Connection reset by peer')
Connection reset by peer
Closing connection with ('48:27:EA:0A:C5:14', 1)
Waiting for connection
Established Connection with ('48:27:EA:0A:C5:14', 1)
BluetoothError occured while waiting or processing command: (104, 'Connection reset by peer')
Traceback (most recent call last):
  File "<string>", line 3, in recv
_bluetooth.error: (104, 'Connection reset by peer')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/repos/vancontrol/raspi/BluetoothController.py", line 61, in _listen
    data = self._client_sock.recv(1024)
  File "<string>", line 5, in recv
bluetooth.btcommon.BluetoothError: (104, 'Connection reset by peer')
Connection reset by peer
Closing connection with ('48:27:EA:0A:C5:14', 1)
Waiting for connection
Established Connection with ('48:27:EA:0A:C5:14', 1)
BluetoothError occured while waiting or processing command: (104, 'Connection reset by peer')
Traceback (most recent call last):
  File "<string>", line 3, in recv
_bluetooth.error: (104, 'Connection reset by peer')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/repos/vancontrol/raspi/BluetoothController.py", line 61, in _listen
    data = self._client_sock.recv(1024)
  File "<string>", line 5, in recv
bluetooth.btcommon.BluetoothError: (104, 'Connection reset by peer')
Connection reset by peer
Closing connection with ('48:27:EA:0A:C5:14', 1)
Waiting for connection
